### ISSUE TITLE
Extend for TBC

### ISSUE THREAD

**Issue by Malspherus** [znibb/WowProfessionLevelingTool#7]
It would be great to be able to look up skilling for Burning Crusade, both Jewelcrafting 1-300 as well as all professions 300-375 even if not all prices can be calculated yet as it allows us to stock up on already available mats

**Comment by znibb** [comment]
I am 100% planning on updating this for BCC. I'm assuming that when the beta goes live there will be reliable profession data available so that I can add JC 1-300 at least. For any prof 300-375 that can't really happen until BCC actually releases since the tool uses the pricing data as a vital component of the algorithm.
